global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'waterbill-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['waterbill-service:8080']    # ← change 'app' to your host IP
    authorization:
      type: Bearer
      credentials: "admin_key_789"