# Basic App Info
spring.application.name=waterbill
management.endpoints.web.exposure.include=health,info,metrics,prometheus
waterbill.excluded-paths=/actuator/**

# --- Waterbill Custom Config ---
waterbill.api-key=water123
waterbill.water-per-person-per-day=10
waterbill.days-in-month=30

# Lists/Arrays (Slabs)
waterbill.slab-capacities=500,1000,1500
waterbill.slab-rates=2,3,5,8

# Rates
waterbill.corporation-rate=1.0
waterbill.borewell-rate=1.5

# Map (BHK to Residents)
waterbill.bhk-to-resident-count.2=3
waterbill.bhk-to-resident-count.3=5

# SQL Server Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Abinithi.1973

# Hibernate Dialect for SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Show DEBUG logs for your specific package
logging.level.com.example.waterbill=DEBUG

# Keep Spring Framework logs at INFO (otherwise your console will explode with text)
logging.level.org.springframework=INFO